"""Single source of truth for the official PubMedQA PQA-L release (`ori_pqal.json`).

`ori_pqal.json` is the only file that ships the two *single-annotator* predictions
next to the multi-annotator gold label, which is what every protocol-audit analysis
in this repo stands on. `data/raw/` is gitignored, so the file cannot be committed;
this module fetches it on demand and pins it by SHA-256, so a report can name the
exact bytes it was computed from.

Annotator roles (Jin et al. 2019, §2.2) — trivially easy to state backwards, and we
did state them backwards in `human_maybe_study.py` until 2026-09-26:

    reasoning_required_pred : annotator saw question + CONTEXTS only, **no conclusion**
    reasoning_free_pred     : annotator also saw the author conclusion (LONG_ANSWER),
                              so no reasoning over the evidence was required

Hence the deliberately blunt aliases below: `CONTEXT_ONLY_FIELD` and
`SEES_CONCLUSION_FIELD`. Prefer them over the raw field names. The direction is
checkable on the released file — the annotator who sees the conclusion agrees with
the gold label 91.6% of the time, the context-only annotator only 78.1% — which is
what `assert_annotator_roles` verifies.

CONTEXTS never contains a conclusion section (0/1000 items have a CONCLUSION-like
`LABELS` entry), so "the model does not see the conclusion" is a property of the
data, not an assumption.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys
from urllib.request import urlopen

PROJECT_ROOT = Path(__file__).resolve().parents[2]

ORI_PQAL_PATH = PROJECT_ROOT / "data/raw/pubmedqa_official/data/ori_pqal.json"
ORI_PQAL_URL = "https://raw.githubusercontent.com/pubmedqa/pubmedqa/master/data/ori_pqal.json"
ORI_PQAL_SHA256 = "8b3276be8942ebbd77f3ddcda12c1749bf0e490045a736fd8438ee40cf37a41d"

# The 500 PQA-L test pmids, already vendored with the benchmark. The upstream repo
# ships no train/dev split of its own (folds are regenerated by its preprocessing
# script), so "not in the test set" is the most precise split label available.
TEST_GROUND_TRUTH_PATH = (
    PROJECT_ROOT / "data/benchmarks/pubmedqa/official_pqal_test/test_ground_truth.json"
)

CONTEXT_ONLY_FIELD = "reasoning_required_pred"
SEES_CONCLUSION_FIELD = "reasoning_free_pred"
GOLD_FIELD = "final_decision"
LABELS = ("yes", "no", "maybe")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download_ori_pqal(path: Path = ORI_PQAL_PATH, url: str = ORI_PQAL_URL) -> Path:
    """Fetch `ori_pqal.json` from the official repo. Idempotent: skips an existing file."""
    if path.exists():
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    with urlopen(url, timeout=120) as response:  # noqa: S310 — pinned https URL
        payload = response.read()
    tmp = path.with_suffix(path.suffix + ".part")
    tmp.write_bytes(payload)
    tmp.replace(path)
    return path


def load_ori_pqal(path: Path = ORI_PQAL_PATH, *, download: bool = True) -> dict[str, dict]:
    """Load the release keyed by pmid, fetching it first if needed.

    A SHA-256 mismatch is a warning, not an error: upstream could legitimately
    re-release the file, and every script that loads it also records the hash it
    actually saw, so a changed hash is traceable rather than silently ignored.
    """
    if not path.exists():
        if not download:
            raise FileNotFoundError(
                f"{path} is missing. Fetch it with `make pqal-fetch`, or call "
                "load_ori_pqal(download=True)."
            )
        download_ori_pqal(path)
    actual = sha256(path)
    if actual != ORI_PQAL_SHA256:
        print(
            f"WARNING: {path.name} sha256 {actual} != pinned {ORI_PQAL_SHA256}. "
            "Numbers in existing reports were computed from the pinned copy.",
            file=sys.stderr,
        )
    return json.loads(path.read_text(encoding="utf-8"))


def test_pmids(path: Path = TEST_GROUND_TRUTH_PATH) -> set[str]:
    return set(json.loads(path.read_text(encoding="utf-8")))


def split_of(pmid: str, test_set: set[str]) -> str:
    return "test" if pmid in test_set else "train_dev"


def assert_annotator_roles(ori: dict[str, dict]) -> dict[str, float]:
    """Guard against re-swapping the two annotator fields.

    Returns each annotator's agreement with the gold label. Raises if the
    context-only annotator scores *higher* than the one who saw the conclusion,
    which would mean the field aliases no longer describe the data.
    """
    agreement = {}
    for field in (CONTEXT_ONLY_FIELD, SEES_CONCLUSION_FIELD):
        hits = sum(1 for v in ori.values() if v[field] == v[GOLD_FIELD])
        agreement[field] = hits / len(ori)
    if agreement[SEES_CONCLUSION_FIELD] <= agreement[CONTEXT_ONLY_FIELD]:
        raise AssertionError(
            "Annotator roles look swapped: "
            f"{SEES_CONCLUSION_FIELD}={agreement[SEES_CONCLUSION_FIELD]:.3f} should exceed "
            f"{CONTEXT_ONLY_FIELD}={agreement[CONTEXT_ONLY_FIELD]:.3f} (Jin et al.: 90.4 vs 78.0)."
        )
    return agreement


def main() -> None:
    """`python scripts/agents/pqal_official.py` — fetch and verify the release."""
    path = download_ori_pqal()
    ori = load_ori_pqal(path)
    agreement = assert_annotator_roles(ori)
    print(f"{path} ({len(ori)} items, sha256 {sha256(path)})")
    for field, value in agreement.items():
        role = "sees conclusion" if field == SEES_CONCLUSION_FIELD else "context only"
        print(f"  {field:24s} ({role:15s}) agrees with {GOLD_FIELD}: {value:.3f}")


if __name__ == "__main__":
    main()
